version: "3.8"

services:
  traffic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic
    volumes:
      - /traffic:/traffic
    cap_add:
      - NET_ADMIN  # 允许抓包所需的权限
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1  # 确保实时输出日志
    command: ["python", "main.py"]  # 容器启动时运行的默认命令

# docker-compose build
# docker-compose up
