version: "3.8"

services:
  traffic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic
    volumes:
      - /traffic:/traffic
    cap_add:
      - NET_ADMIN  # 允许抓包所需的权限
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1  # 确保实时输出日志
    depends_on:
      - minio  # 依赖 MinIO 服务
    command: ["python", "server.py"]  # 容器启动时运行的默认命令

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Web Console
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - /mnt/minio/data:/data
    command: server /data --console-address ":9001"

  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin password;
      /usr/bin/mc mb myminio/traffic;
      tail -f /dev/null
      "


# docker-compose build
# docker-compose up
# docker-compose down --volumes
# docker system prune -a -f
# docker-compose up traffic

